# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa8873a893b8bb8f6525a94749f39b9c605a0f9e2446e40e7e0c38baac43fd8ce2e9baccae65b27a0d64877548db2a7b6303addeaff4700ee9f39913dadde8a

test:
  secret_key_base: 110f0d96079928a58b95a626e7c7fad4eab971d0316492be809b65e1a2ed7951ebddafad724c876e4b8cb455a043be8d646da1e0f0a78dca7cc886236192be3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
